### ISSUE TITLE
Import crash in `remove_empty_shapekeys_vertex_groups` when `obj.data` is None (`clean_empty_mesh_data`)

### ISSUE THREAD

**Issue by RaincloudTheDragon** [soupday/cc_blender_tools#400]
## Summary

Character import fails when **“Clean empty mesh shape-keys and vertex groups on import”** is enabled (default). The importer calls `remove_empty_shapekeys_vertex_groups()` on armature children that have no mesh datablock (`obj.data is None`), causing:

```
AttributeError: 'NoneType' object has no attribute 'shape_keys'
```

## Environment

- **Add-on:** CC/iC Blender Tools **2.4.2** (`cc_blender_tools-2_4_2`), confirmed in 2.4.1 and 2.4.0 as well, worked in 2.3.4.
- **Blender:** 4.5, 5.0, 5.1, and 5.2 (reproduced on all)
- **Source app:** Character Creator 5, export via **Plugins → Blender Pipeline** (FBX + JSON)
- **CC/iC plugin:** CC/iC Blender Pipeline Plugin **2.4.2** (installed in CC5 `OpenPlugin`)

## Traceback

```
File ".../cc_blender_tools-2_4_2/importer.py", line 1140, in import_character
    characters.remove_empty_shapekeys_vertex_groups(arm, obj)
File ".../cc_blender_tools-2_4_2/characters.py", line 1802, in remove_empty_shapekeys_vertex_groups
    if obj.data.shape_keys:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape_keys'
```

## Steps to reproduce

1. Install add-on 2.4.2.
2. Leave **Clean empty mesh shape-keys and vertex groups on import** enabled (default in preferences).
3. Export a character from CC5 via Blender Pipeline (FBX + JSON).
4. Import into Blender via CC/iC Tools.

Import fails during post-import cleanup.

## Expected behavior

Import completes. Non-mesh or mesh-less objects are skipped during empty shape-key / vertex-group cleanup.

## Actual behavior

Import aborts with the traceback above.

## Analysis

There’s an inconsistency between the **manual** clean path and the **auto-on-import** path.

**Manual** (`remove_all_empty_shapekeys_vertex_groups` in `characters.py`) filters meshes:

```python
if obj not in body_objects and obj.type == "MESH":
    kc, gc = remove_empty_shapekeys_vertex_groups(arm, obj)
```

**Auto on import** (`importer.py` ~1136–1140) does not:

```python
if prefs.clean_empty_mesh_data:
    for obj in imported:
        if obj.parent and obj.parent.type == "ARMATURE":
            characters.remove_empty_shapekeys_vertex_groups(arm, obj)
```

And `remove_empty_shapekeys_vertex_groups()` assumes `obj.data` exists:

```python
if obj.data.shape_keys:
```

Some armature children in the import set have `obj.data is None` (empties/helpers or mesh-less objects), which triggers the crash.

This appears to have been introduced when auto-clean-on-import was added in **2.4.0** (`clean_empty_mesh_data`); still present in **2.4.2** on `main`.

## Suggested fix

Either or both:

**1. In `remove_empty_shapekeys_vertex_groups()`:**

```python
if obj.type != "MESH" or obj.data is None:
    return key_count, group_count
if obj.data.shape_keys:
    ...
```

**2. In `importer.py`, match the manual path:**

```python
if obj.parent and obj.parent.type == "ARMATURE" and obj.type == "MESH" and obj.data:
    characters.remove_empty_shapekeys_vertex_groups(arm, obj)
```

## Workaround

Disable **Clean empty mesh data on import** in add-on preferences, then re-import. This is a trade-off, given that it imports the character without proper rotation and scale.
